### ISSUE TITLE
Latest changes do not compile in droidmediacodec.cpp

### ISSUE THREAD

**Issue by Flohack74** [sailfishos/droidmedia#84]
According to our CI your change at https://github.com/sailfishos/droidmedia/commit/4e40a44b2b0a9c0ed6d328115a9c8fd9737f857d#diff-e1bdd5492dd0f95748bb1bdf8102ade83920a862c015d87338df05366935231bR782 broke compilation: See end of log at https://ci.ubports.com/job/UBportsCommunityPortsJenkinsCI/job/ubports%2Fcommunity-ports%2Fjenkins-ci%2Fmarlin-sailfish/job/main/149/console

**Comment by d-grigorev** [comment]
The issue should be fixed with https://github.com/sailfishos/droidmedia/commit/2d80398f2190150c12fce834d2c9c58851ee25f0 tagged as `0.20210812.1`.

**Comment by Flohack74** [comment]
Ok I trigger a test build now...

**Comment by Flohack74** [comment]
Alright fixed, thx!
