### ISSUE TITLE
where can I find the "droid-make" command?

### ISSUE THREAD

**Issue by TuQinggang** [sailfishos/droidmedia#88]
![image](https://user-images.githubusercontent.com/24808608/130543260-0e609016-2c47-40e1-ae3a-ecfeab98b138.png)
Hello, I am building this package,I have resolved the dependeces,but I still can't find the command "droid-make". :sos: 
my OS info:
  NAME="Ubuntu"
  VERSION="20.04.2 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
my SDK info:
  SDK_RELEASE=3.5.7
  SDK_RELEASE_CYCLE=Stable
  SDK_CONFIG_DIR=SailfishSDK
  SDK_VENDOR="Jolla"

Please tell me how can I get the droid-make command.
Thanks! :sunflower:

**Comment by mlehtima** [comment]
That droid-make is not normal command which people should be using, it's a special command used in OBS (Open Build Service) builds. The spec file in this repo is made only for OBS builds. The normal way to build is instructed in Sailfish OS HADK pdf (https://sailfishos.org/develop/hadk/).

**Comment by rainemak** [comment]
@TuQinggang : have you received enough input from @mlehtima? I'm considering this issue as closed. Please open follow up question as per need.
